sudo: required

services:
  - docker

language: go
go: 1.10.x

script:
  - docker build -t sct .
  - docker run --rm -it sct ./test.sh

addons:
  apt:
    packages:
    - xorg-dev
    - libglu1-mesa-dev

